# Generated by Django 3.2.5 on 2021-07-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
