# Generated by Django 3.2.5 on 2021-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
