# Generated by Django 3.2.5 on 2021-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
