# Generated by Django 3.2.5 on 2021-08-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nowhelp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
