# Generated by Django 3.2.5 on 2021-08-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nowhelp', '0002_delete_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=1000)),
                ('ad_or_user', models.CharField(max_length=10)),
                ('client_dtls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nowhelp.clientdtls')),
            ],
        ),
    ]
