# Generated by Django 3.2.5 on 2021-07-18 11:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('keywords', models.TextField()),
                ('slug', models.CharField(max_length=10)),
                ('published', models.BooleanField()),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.posts')),
            ],
        ),
    ]
